.DEFAULT_GOAL := info

info:
	@echo init, show, plan, apply, destroy, state_list, output

init:
	terraform init

show:
	terraform show

plan:
	terraform plan

apply:
	terraform apply

desploy:
	terraform destroy

state_list:
	terraform state list

output:
	terraform output